// ============ NEXUS DATA ============
const COLOR_MAP = {
  red:{c:'#ff3860',glow:'rgba(255,56,96,.35)',bg:'rgba(255,56,96,.07)',border:'rgba(255,56,96,.35)'},
  green:{c:'#00ff88',glow:'rgba(0,255,136,.35)',bg:'rgba(0,255,136,.07)',border:'rgba(0,255,136,.35)'},
  orange:{c:'#ff9f1c',glow:'rgba(255,159,28,.35)',bg:'rgba(255,159,28,.07)',border:'rgba(255,159,28,.35)'},
  teal:{c:'#1f9e8e',glow:'rgba(31,158,142,.35)',bg:'rgba(31,158,142,.07)',border:'rgba(31,158,142,.35)'},
  qgreen:{c:'#23963c',glow:'rgba(35,150,50,.35)',bg:'rgba(35,150,50,.07)',border:'rgba(35,150,50,.35)'},
  gred:{c:'#c83232',glow:'rgba(200,50,50,.35)',bg:'rgba(200,50,50,.07)',border:'rgba(200,50,50,.35)'},
  pink:{c:'#f48fb1',glow:'rgba(244,143,177,.35)',bg:'rgba(244,143,177,.07)',border:'rgba(244,143,177,.35)'},
  purple:{c:'#b388ff',glow:'rgba(179,136,255,.35)',bg:'rgba(179,136,255,.07)',border:'rgba(179,136,255,.35)'},
  lime:{c:'#69ff47',glow:'rgba(105,255,71,.35)',bg:'rgba(105,255,71,.07)',border:'rgba(105,255,71,.35)'},
  cyan:{c:'#00e5ff',glow:'rgba(0,229,255,.35)',bg:'rgba(0,229,255,.07)',border:'rgba(0,229,255,.35)'},
  yellow:{c:'#ffd60a',glow:'rgba(255,214,10,.35)',bg:'rgba(255,214,10,.07)',border:'rgba(255,214,10,.35)'},
  crimson:{c:'#dc143c',glow:'rgba(220,20,60,.35)',bg:'rgba(220,20,60,.07)',border:'rgba(220,20,60,.35)'},
  deeporange:{c:'#ff5722',glow:'rgba(255,87,34,.35)',bg:'rgba(255,87,34,.07)',border:'rgba(255,87,34,.35)'},
  lightblue:{c:'#4fc3f7',glow:'rgba(79,195,247,.35)',bg:'rgba(79,195,247,.07)',border:'rgba(79,195,247,.35)'},
  skyblue:{c:'#87ceeb',glow:'rgba(135,206,235,.35)',bg:'rgba(135,206,235,.07)',border:'rgba(135,206,235,.35)'},
  periwinkle:{c:'#8f9eff',glow:'rgba(143,158,255,.35)',bg:'rgba(143,158,255,.07)',border:'rgba(143,158,255,.35)'},
  violet:{c:'#9d4edd',glow:'rgba(157,78,221,.35)',bg:'rgba(157,78,221,.07)',border:'rgba(157,78,221,.35)'},
};

const SECTIONS = {
  tools:{ name:'Tools & Applications', accent:'teal',
    title:'Professional Cybersecurity Analysis Tools',
    desc:'Tools to detect threats, analyze files, verify emails, scan URLs, and protect yourself online.' },
  quizzes:{ name:'Quizzes', accent:'qgreen',
    title:'Test & Build Your Cyber Awareness',
    desc:'Learning-based quizzes covering passwords, phishing, Wi-Fi security, privacy, and cyber knowledge.' },
  games:{ name:'Games Lab', accent:'gred',
    title:'Hands-On Cyber Games & Labs',
    desc:'Interactive games and labs that teach cybersecurity through play.' },
};

const ITEMS = {
  // ===== TOOLS =====
  url:{ section:'tools', color:'red', icon:'🔗', name:'URL Analyzer', short:'Detect phishing & malicious links',
    what:'Inspects any web link using 11 heuristic checks (homograph/punycode detection, brand impersonation, suspicious TLDs, redirect params, and more) and cross-checks it against Google\'s real Safe Browsing threat database.',
    why:'Cybercriminals send millions of fake links every day disguised as banks, shopping sites, and government portals. One wrong click can steal your credentials or install malware.',
    how:'Paste any suspicious link and get an instant risk score (0–100) with a full breakdown of every red flag detected, plus a real-time Google Safe Browsing verdict.',
    btn:'ANALYZE A URL NOW', type:'tool' },
  password:{ section:'tools', color:'green', icon:'🔑', name:'Password Checker', short:'Evaluate password strength & entropy',
    what:'Evaluates how strong or weak any password is using entropy calculations, pattern detection (sequential runs, keyboard walks, word+year combos), and a common-password blocklist.',
    why:'Over 80% of data breaches involve weak or reused passwords. Most people use passwords that can be cracked in under a second.',
    how:'Type any password and get a strength score, entropy value, and specific suggestions to make it unbreakable.',
    btn:'CHECK MY PASSWORD', type:'tool' },
  email:{ section:'tools', color:'orange', icon:'📧', name:'Email Verifier', short:'Identify fake or disposable emails',
    what:'Checks whether an email address is real, disposable, auto-generated, role-based, or from a known temporary mail service — and verifies the domain can actually receive mail.',
    why:'Scammers use throwaway emails to create fake accounts and send phishing campaigns that are hard to track.',
    how:'Enter any email address and get a risk assessment covering format, domain patterns, disposable services, and a real mail-server (MX) check.',
    btn:'VERIFY AN EMAIL', type:'tool' },
  forensics:{ section:'tools', color:'purple', icon:'🕵️', name:'Forensics Analyzer', short:'Real EXIF, steganography & ELA tamper detection',
    what:'Extracts real hidden metadata from images (GPS, timestamp, camera model), runs genuine pixel-level steganography detection, and generates a real Error Level Analysis heatmap to spot edited regions.',
    why:'Images shared online often contain hidden GPS coordinates and timestamps. Edited images used as evidence can be detected through ELA analysis.',
    how:'Upload any image. The tool extracts real EXIF metadata, analyzes pixel data for hidden content, and produces a visual tamper heatmap — all in your browser.',
    btn:'ANALYZE AN IMAGE', type:'tool' },
  qr:{ section:'tools', color:'yellow', icon:'▣', name:'QR Code Scanner', short:'Scan & decode real QR codes from images',
    what:'Decodes real QR codes directly from an uploaded photo and automatically runs any embedded URL through the phishing detector.',
    why:'QR phishing ("quishing") is a fast-growing attack. Criminals place fake QR codes on posters and menus to redirect victims to malicious sites.',
    how:'Upload a photo containing a QR code — the tool decodes it directly in your browser and checks any URL for threats.',
    btn:'SCAN A QR CODE', type:'tool' },
  headers:{ section:'tools', color:'deeporange', icon:'📨', name:'Email Header Analyzer', short:'Detect email spoofing & SPF/DKIM',
    what:'Parses raw email headers to check SPF, DKIM, and DMARC authentication, plus display-name spoofing and Return-Path mismatches.',
    why:'Anyone can send an email pretending to be your bank. Email headers reveal whether the sender is who they claim to be.',
    how:'Copy raw headers from any email (Gmail: 3-dot menu, Show original) and paste them here.',
    btn:'ANALYZE HEADERS', type:'tool' },
  ip:{ section:'tools', color:'lightblue', icon:'🌐', name:'IP Address Lookup', short:'Geolocation, ISP info & reverse DNS',
    what:'Looks up geolocation, ISP, organization, reverse DNS hostname, and proxy/VPN status for any IP address, with plain-English risk framing.',
    why:'IP addresses can reveal the location of servers, identify malicious hosts, and help trace cyberattacks.',
    how:'Enter any IP address and get its country, city, ISP, organization, hostname, and a plain-English risk note.',
    btn:'LOOKUP AN IP', type:'tool' },
  fingerprint:{ section:'tools', color:'crimson', icon:'🫆', name:'Browser Fingerprint Checker', short:'See how trackable your browser really is',
    what:'Analyzes your real browser session — user agent, screen size, timezone, language, fonts, and canvas rendering — to show how uniquely identifiable you are, even without cookies.',
    why:'Trackers don\'t need cookies to follow you. The combination of harmless-looking browser details is often unique enough to identify you individually across the entire web.',
    how:'Just open the tool — it instantly analyzes your current browser and shows your real fingerprint data plus a uniqueness estimate.',
    btn:'CHECK MY FINGERPRINT', type:'tool' },
  encrypt_playground:{ section:'tools', color:'skyblue', icon:'🧬', name:'Encryption Playground', short:'Watch text transform through real ciphers',
    what:'Type any message and watch it transform step-by-step through three different encryption methods side by side — Caesar shift, XOR, and a simplified substitution cipher.',
    why:'Modern encryption feels abstract until you actually watch text get scrambled. Seeing several methods side by side makes clear why some are trivial to break and others aren\'t.',
    how:'Type a message, pick a method, and watch the transformation happen live with a step-by-step breakdown.',
    btn:'OPEN PLAYGROUND', type:'tool' },
  metadata_strip:{ section:'tools', color:'periwinkle', icon:'🧹', name:'Metadata Stripper', short:'Remove hidden data from your photos',
    what:'Shows you exactly what hidden metadata (GPS, device model, timestamp) is embedded in a photo, then lets you download a cleaned version with that data removed.',
    why:'Photos you post online can silently reveal your exact location and device. This is the protective counterpart to Forensics Analyzer — instead of detecting hidden data, it removes it from your own files.',
    how:'Upload a photo. See its real embedded metadata, then download a stripped, safe-to-share version.',
    btn:'STRIP METADATA', type:'tool' },

  // ===== QUIZZES =====
  wifi_quiz:{ section:'quizzes', color:'lime', icon:'📡', name:'Wi-Fi & Network Security Quiz', short:'MCQ test on network security concepts',
    what:'A multiple-choice quiz testing real understanding of Wi-Fi and network security — not a self-audit checklist, but genuine concept testing.',
    why:'Most home routers ship with default passwords and insecure settings. Understanding why matters more than just being told what to change.',
    how:'Answer MCQ questions on WPA3, WPS, rogue access points, and more. Every answer is explained.',
    btn:'START QUIZ', type:'quiz' },
  password_quiz:{ section:'quizzes', color:'cyan', icon:'🧠', name:'Password Strength Quiz', short:'MCQ test on password security',
    what:'A multiple-choice quiz that tests your knowledge of password security best practices.',
    why:'Most people don\'t know what actually makes a password strong. Understanding this is the first step to protecting all your accounts.',
    how:'Swipe through MCQ questions. Each answer is explained so you learn as you go.',
    btn:'START QUIZ', type:'quiz' },
  cyber_iq:{ section:'quizzes', color:'purple', icon:'🤖', name:'Cyber IQ Test', short:'Cyber knowledge test',
    what:'A test covering a broad range of cybersecurity topics — from malware to encryption to social engineering.',
    why:'Cybersecurity awareness is a core life skill in the digital age. Knowing your weak spots helps you focus your learning.',
    how:'Swipe through MCQ questions. Your final score determines your Cyber IQ rating.',
    btn:'TEST MY CYBER IQ', type:'quiz' },
  social_eng:{ section:'quizzes', color:'orange', icon:'🎭', name:'Social Engineering Quiz', short:'Identify manipulation tactics',
    what:'A scenario-based quiz where you identify manipulation tactics used by cybercriminals in real-world situations.',
    why:'Social engineering bypasses all technical security. Attackers manipulate people, not systems.',
    how:'Read realistic scenarios and identify the manipulation technique being used.',
    btn:'START QUIZ', type:'quiz' },
  darkweb:{ section:'quizzes', color:'violet', icon:'🕸️', name:'Dark Web Awareness Quiz', short:'Myths vs facts about the dark web',
    what:'A quiz that separates myths from facts about the dark web and how your data ends up there.',
    why:'Billions of stolen credentials are sold on dark web markets every year.',
    how:'Answer MCQ questions about the dark web, each with a real-fact explanation.',
    btn:'START QUIZ', type:'quiz' },
  incident:{ section:'quizzes', color:'red', icon:'🚨', name:'Incident Response Quiz', short:'What to do when you get hacked',
    what:'A scenario-based quiz testing what you would do if you got hacked, infected with ransomware, or had your identity stolen.',
    why:'Most people panic when a cyber incident happens and make it worse. Knowing the correct steps limits damage.',
    how:'Face realistic cyber incident scenarios and choose the best response.',
    btn:'START QUIZ', type:'quiz' },
  hygiene:{ section:'quizzes', color:'lime', icon:'🧹', name:'Digital Hygiene Quiz', short:'MCQ test on daily safety habits',
    what:'A multiple-choice quiz on the daily digital habits that actually keep you safe online.',
    why:'Good digital hygiene prevents the majority of cyber incidents — understanding why each habit matters makes it stick.',
    how:'Answer MCQ questions on updates, 2FA, backups, and more. Every answer is explained.',
    btn:'START QUIZ', type:'quiz' },
  privacy:{ section:'quizzes', color:'lime', icon:'🔒', name:'Privacy & Data Protection Quiz', short:'MCQ test on data privacy',
    what:'A multiple-choice quiz on how your data really gets collected, tracked, and exposed online.',
    why:'Default privacy settings on most platforms expose your data to strangers and advertisers — few people understand exactly how.',
    how:'Answer MCQ questions on data brokers, metadata, tracking cookies, and more.',
    btn:'START QUIZ', type:'quiz' },
  device_quiz:{ section:'quizzes', color:'lime', icon:'💻', name:'Device & Mobile Security Quiz', short:'MCQ test on device security',
    what:'A multiple-choice quiz testing real understanding of phone and laptop security concepts.',
    why:'Most people know device security matters but not why specific settings (encryption, screen locks, permissions) actually protect them.',
    how:'Answer MCQ questions on encryption, permissions, Bluetooth, and more.',
    btn:'START QUIZ', type:'quiz' },
  digital_footprint:{ section:'quizzes', color:'skyblue', icon:'👣', name:'Digital Footprint Awareness Quiz', short:'How exposed is your identity online?',
    what:'A quiz covering EXIF metadata, deleted-content myths, username correlation, doxxing, and routine-based exposure.',
    why:'Most people have no idea how much of their identity is discoverable through public information alone.',
    how:'Answer MCQ questions and learn exactly how strangers piece together profiles from public data.',
    btn:'START QUIZ', type:'quiz' },

  // ===== GAMES =====
  cipher:{ section:'games', color:'pink', icon:'🔐', name:'Caesar Cracker', short:'Decode shifted messages, no clock',
    what:'A Caesar cipher shifts every letter of a message forward by a fixed number of positions — this game shows you a shifted message and challenges you to decode it back.',
    why:'The Caesar cipher is one of the oldest known encryption methods. Modern encryption is far more complex, but built on the same core idea.',
    how:'Round 1 is an untimed practice round with a worked example. Then 10 untimed rounds — decode each message, use Hint anytime, or Skip if you\'re stuck. Get 7 or more right to win.',
    btn:'PLAY CAESAR CRACKER', type:'game' },
  crack_code:{ section:'games', color:'pink', icon:'🕵️', name:'Crack the Code', short:'Guess the Caesar shift, 5 rounds',
    what:'A puzzle game where you\'re given a Caesar-encrypted phrase and must figure out the correct shift to decode it, across 5 rounds with a limited number of guesses each.',
    why:'Frequency analysis and pattern recognition are core cryptanalysis skills.',
    how:'Adjust the shift slider until the live preview makes sense, then submit. You get 8 guesses per round across 5 rounds.',
    btn:'START CRACKING', type:'game' },
  phishing_detect:{ section:'games', color:'pink', icon:'🎣', name:'Phishing Detective', short:'Spot the fake URL',
    what:'A game where you\'re shown sets of URLs across banking, social media, delivery, and government categories, and must identify which one is the phishing link.',
    why:'The best defense against phishing is a trained eye. This game makes spotting fake URLs second nature.',
    how:'Each round shows you 3 URLs in a random order. One is a phishing link. Click the one you think is fake across 8 rounds.',
    btn:'PLAY NOW', type:'game' },
  morse:{ section:'games', color:'pink', icon:'📡', name:'Morse Rush', short:'Decode Morse with a reference chart',
    what:'Shows you a word in Morse code and challenges you to decode it — with a full Morse reference chart always visible on-screen.',
    why:'Morse code is still actively used in aviation and amateur radio. This game builds real pattern recognition, not memorization pressure.',
    how:'Round 1 is an untimed practice round. Then 10 untimed rounds with the reference chart open at all times — decode, hint, or skip. Get 7 or more right to win.',
    btn:'PLAY MORSE RUSH', type:'game' },
  binary:{ section:'games', color:'pink', icon:'💻', name:'Binary Blitz', short:'Decode binary using riddle clues',
    what:'Each round gives you a short riddle (like "What do you do at a green light?") plus its answer in binary — so you can often guess the word from context, then verify using the code.',
    why:'Binary is the fundamental language of every computer. This game teaches it through inference, not raw ASCII memorization.',
    how:'Round 1 is an untimed practice round. Then 10 untimed rounds — read the riddle, decode the binary, use the first-letter hint if stuck, or skip. Get 7 or more right to win.',
    btn:'PLAY BINARY BLITZ', type:'game' },
  passgen:{ section:'games', color:'pink', icon:'🔑', name:'Password Generator Game', short:'Build a password that passes every rule',
    what:'A game where you generate the strongest possible password following a randomized set of rules, with live checkmarks as you type and a limited number of attempts.',
    why:'Making strong passwords is a skill. This game builds that muscle memory in a fun, real-time format.',
    how:'Get 4 rules from a large pool. Type a password — checkmarks update live. You get 6 attempts to satisfy every rule.',
    btn:'PLAY NOW', type:'game' },
  escape_room:{ section:'games', color:'pink', icon:'🚪', name:'Cyber Escape Room', short:'Solve 5 puzzles to escape',
    what:'A text-based puzzle game where you must solve 5 randomly-selected cybersecurity puzzles (from a larger pool) to escape a locked system, with forgiving answer matching.',
    why:'Escape rooms build problem-solving under pressure — a key skill for security analysts.',
    how:'Face 5 puzzles covering ciphers, attack identification, phishing, passwords, and protocols. You get 4 attempts per puzzle.',
    btn:'ENTER THE ROOM', type:'game' },
  threat_triage:{ section:'games', color:'pink', icon:'🧯', name:'Threat Triage', short:'Categorize real-world scenarios fast',
    what:'You\'re shown a short real scenario — a text message, an email snippet, a phone call — and must categorize it correctly: Phishing, Malware, Social Engineering, or Legitimate.',
    why:'This is the "final boss" game — it pulls together everything learned across every tool and quiz in NEXUS into one fast recognition test.',
    how:'Read each scenario and tap the correct category. Instant feedback explains why. 10 rounds, get 7 or more right to win.',
    btn:'START TRIAGE', type:'game' },
  redflag_hunter:{ section:'games', color:'pink', icon:'🚩', name:'Red Flag Hunter', short:'Click the red flags in fake emails & pages',
    what:'You\'re shown a realistic mockup of a phishing email or fake login page and must click directly on the actual red flags in it — the mismatched sender, the urgent subject, the wrong URL.',
    why:'Real phishing attacks are visual. This is the one game where you interact with something spatially instead of typing or choosing an answer — often more memorable.',
    how:'Click every part of the mockup you think is suspicious. Correct clicks score points, wrong clicks cost points. See everything you missed at the end of each round.',
    btn:'START HUNTING', type:'game' },
  scamcall_sim:{ section:'games', color:'pink', icon:'📞', name:'Scam Call Simulator', short:'Navigate a live fake scam call',
    what:'A simulated phone call plays out as a scrolling transcript. At key moments you choose how to respond — and different choices branch the conversation differently.',
    why:'Scam calls rely on you staying on the line and complying under pressure. Practicing the right responses in a safe simulation builds real instinct.',
    how:'Read the transcript as it unfolds and pick your response at each decision point. Wrong choices show you exactly how the scam would have escalated.',
    btn:'ANSWER THE CALL', type:'game' },
};

const HOW_TO = {
  url:{steps:['Copy any suspicious URL from an email, message, or website','Paste it into the input field','Click ANALYZE URL and wait for the risk score','Review the score (0-100), the flagged issues, and the Google Safe Browsing badge'],
    demoIn:'http://paypal-secure-login.tk/verify',demoOut:'HIGH RISK — Score: 91/100',
    works:'Runs 11 heuristic checks (HTTPS, homograph/punycode, brand impersonation, TLD reputation, redirect params, and more) and separately queries Google\'s real Safe Browsing API via a secure serverless endpoint — if that call fails, the heuristic score still works standalone.'},
  password:{steps:['Type your password in the input box','Click ANALYZE PASSWORD','Review score, entropy and character breakdown','Read improvement suggestions'],
    demoIn:'Summer2024!',demoOut:'Strength: FAIR — Score: 48/100',
    works:'Calculates Shannon entropy, checks character variety, detects keyboard-walk and sequential-run patterns, flags common word+year combos, and matches against a common-password list.'},
  email:{steps:['Type an email address','Click VERIFY EMAIL','Review all checks','Red = suspicious, Green = legitimate'],
    demoIn:'winner.prize2024@mailinator.com',demoOut:'SUSPICIOUS — disposable email domain',
    works:'Checks format, disposable-domain list, plus-addressing abuse, random-looking local parts, role-based labeling, and a real MX-record check confirming the domain can actually receive mail.'},
  forensics:{steps:['Upload any image file','Wait for EXIF, steganography, and ELA analysis to complete','Review GPS/timestamp/camera metadata if present','Check the ELA heatmap for signs of digital editing'],
    demoIn:'photo.jpg',demoOut:'GPS: 28.6°N 77.2°E — LSB anomaly: Low — ELA: No tampering detected',
    works:'Uses a real client-side EXIF-reading library for metadata, analyzes canvas pixel data\'s least-significant bits for steganography, and re-compresses the image via canvas to generate a genuine Error Level Analysis heatmap — all in your browser.'},
  qr:{steps:['Upload a photo containing a QR code','The tool decodes it directly in your browser','Review the content type (URL, Wi-Fi, UPI, etc.)','If it\'s a URL, see the automatic phishing risk check'],
    demoIn:'[uploaded QR image]',demoOut:'Decoded: https://example.com — LOW RISK',
    works:'Reads the uploaded image onto a canvas and decodes the actual QR pattern from pixel data using a real QR-decoding library, then classifies the content and runs URL-type content through the URL Analyzer.'},
  headers:{steps:['Open the email you want to check','Find "Show Original" (Gmail) or "Internet Headers" (Outlook)','Copy the raw header text','Paste it here and click ANALYZE HEADERS'],
    demoIn:'From: "PayPal" <fake@random-domain.tk>...',demoOut:'HIGH RISK — Display-name spoofing detected',
    works:'Parses SPF/DKIM/DMARC results, checks From/Reply-To/Return-Path domain mismatches, and flags display-name spoofing where the friendly name doesn\'t match the sending domain.'},
  ip:{steps:['Enter any IPv4 address','Click LOOKUP IP','Review geolocation, ISP, and organization','Check the reverse DNS hostname and risk note'],
    demoIn:'8.8.8.8',demoOut:'Google LLC — Mountain View, US — dns.google',
    works:'Validates the IP format, queries a free public geolocation API for ISP/org/proxy data, and performs a reverse DNS (PTR) lookup via Google\'s public DNS API to resolve the hostname.'},
  fingerprint:{steps:['Open the tool — no input needed','Review your real browser/device fingerprint data','Check your uniqueness estimate','Learn what each data point reveals'],
    demoIn:'[automatic]',demoOut:'Fingerprint uniqueness: ~1 in 280,000 browsers',
    works:'Reads real browser properties (user agent, screen resolution, timezone, language, canvas rendering signature) directly from the browser APIs and combines them into a rough uniqueness estimate.'},
  encrypt_playground:{steps:['Type any short message','Choose Caesar, XOR, or Substitution','Watch the step-by-step transformation','Compare how each method scrambles the same text differently'],
    demoIn:'HELLO',demoOut:'Caesar(3): KHOOR — XOR: scrambled bytes — Substitution: mapped text',
    works:'Implements three real, working transformations client-side and visualizes each step, showing why simple substitution/shift ciphers are trivially reversible while properly keyed methods are not.'},
  metadata_strip:{steps:['Upload a photo','Review exactly what hidden metadata it contains','Click to generate a cleaned version','Download the stripped file'],
    demoIn:'vacation.jpg',demoOut:'Removed: GPS coordinates, device model, timestamp',
    works:'Reads real EXIF metadata for display, then re-draws the image onto a blank canvas and exports it as a new file — canvas re-export does not carry over EXIF data, producing a genuinely metadata-free copy.'},
  wifi_quiz:{steps:['Read each question','Pick the best answer','Get instant explanation','See your final score'],
    demoIn:'Why is WPA3 better than WEP?',demoOut:'Correct: WEP can be cracked in minutes; WPA3 uses much stronger encryption',
    works:'Tests understanding of WPA3/WEP, WPS vulnerabilities, rogue access points, evil twins, network segmentation, and public Wi-Fi risk — not self-reported habits.'},
  password_quiz:{steps:['Read each question','Pick the best answer','Get instant explanation','See final score'],
    demoIn:'What makes a password strong?',demoOut:'Correct: Length! Explanation shown',
    works:'Each question targets a specific password security concept, with an explanation reinforcing the correct concept regardless of your answer.'},
  cyber_iq:{steps:['Read each question','Pick your answer','Learn from the explanation','Get your Cyber IQ score'],
    demoIn:'What is ransomware?',demoOut:'Correct: Malware that encrypts files for payment',
    works:'Covers malware, encryption, social engineering, networking and authentication concepts across 10 weighted questions.'},
  social_eng:{steps:['Read each real-world scenario','Identify the manipulation technique','Read the explanation','See your final score'],
    demoIn:'Fake IT support asks for your password',demoOut:'Correct: Pretexting',
    works:'Tests recognition of pretexting, urgency/fear manipulation, tailgating, quid pro quo, and spear phishing across realistic scenarios.'},
  darkweb:{steps:['Read each question','Pick the best answer','Learn the real fact','See your final score'],
    demoIn:'Does the dark web require a special browser?',demoOut:'Correct: Yes — Tor Browser',
    works:'Separates dark web myths from facts, covering breach dumps, credential stuffing, and how researchers monitor leaked data.'},
  incident:{steps:['Read each incident scenario','Choose your first response','Learn the correct incident-response step','See your final score'],
    demoIn:'Ransomware just hit your PC — first move?',demoOut:'Correct: Disconnect from the network immediately',
    works:'Tests the Detect → Contain → Eradicate → Recover → Review framework across realistic incident scenarios.'},
  hygiene:{steps:['Read each question','Pick the best answer','Get instant explanation','See your final score'],
    demoIn:'Why do software updates matter for security?',demoOut:'Correct: They patch known vulnerabilities attackers actively exploit',
    works:'Tests understanding of update hygiene, 2FA, permissions, backups, and safe-link habits — not self-reported checklist answers.'},
  privacy:{steps:['Read each question','Pick the best answer','Get instant explanation','See your final score'],
    demoIn:'What is a "data broker"?',demoOut:'Correct: A company that collects and sells personal data from many sources',
    works:'Tests understanding of data brokers, metadata exposure, tracking cookies, anonymization limits, and privacy-setting habits.'},
  device_quiz:{steps:['Read each question','Pick the best answer','Get instant explanation','See your final score'],
    demoIn:'What does encryption at rest protect on a stolen phone?',demoOut:'Correct: Someone extracting storage and reading files without your passcode',
    works:'Tests understanding of device encryption, PIN strength, Bluetooth risk, AirDrop exposure, and app permission hygiene.'},
  digital_footprint:{steps:['Read each question about online privacy and footprints','Pick the answer you believe is correct','Read the explanation to understand the real-world risk','Get your score and a checklist of ways to shrink your footprint'],
    demoIn:'"Is a deleted photo really gone?"',demoOut:'Correct: Not necessarily — caches, archives, screenshots',
    works:'Covers EXIF metadata, username correlation, doxxing, account hygiene, and routine-pattern exposure.'},
  cipher:{steps:['Play the untimed practice round first','Then decode 10 messages, one at a time','Use Hint if stuck, or Skip to move on','Get 7 or more correct to win'],
    demoIn:'EDJ (shift 3)',demoOut:'BAG',
    works:'Applies a Caesar shift to a real word bank, with the shift value randomized every playthrough so the pattern can\'t be memorized.'},
  crack_code:{steps:['Read the encrypted phrase','Adjust the shift slider — the live preview updates as you go','Submit your guess','You get 8 guesses per round, across 5 rounds'],
    demoIn:'Puzzle: "KHOOR ZRUOG"',demoOut:'Shift 3 → "hello world"',
    works:'Applies a random Caesar shift to a phrase from an expanded phrase bank; the slider live-decodes so you can visually converge on the right shift through trial and error.'},
  phishing_detect:{steps:['Each round shows 3 URLs in random order','One is phishing — click the one you think is fake','Read the explanation','Continue through all 8 rounds'],
    demoIn:'3 URLs shown',demoOut:'Correct pick + explanation of the red flag',
    works:'The fake URL\'s position is randomized every round so the game tests real recognition, not pattern memorization, across banking, social media, delivery, and government-themed scenarios.'},
  morse:{steps:['Play the untimed practice round first','Use the reference chart (always visible) to decode each word','Use Hint if stuck, or Skip to move on','Get 7 or more correct to win'],
    demoIn:'... --- ...',demoOut:'SOS',
    works:'Maps each letter to its standard Morse pattern via a lookup table; a full reference chart stays visible throughout so no prior memorization is required.'},
  binary:{steps:['Play the untimed practice round first','Read the riddle clue for each round','Use the binary code to verify your guess','Get 7 or more correct to win'],
    demoIn:'Riddle: "What do you do at a green light?"',demoOut:'GO (binary: 01000111 01001111)',
    works:'Each round pairs a short riddle with its answer encoded in binary — you can often infer the word from context, then confirm using the code and a first-letter hint.'},
  passgen:{steps:['Read the 4 randomized password rules shown','Type a password — checkmarks update live as you type','Submit to lock in your attempt','You get 6 attempts to satisfy every rule'],
    demoIn:'Rule: "At least 14 characters, 2 uppercase, 2 numbers"',demoOut:'4/4 rules passed — WON!',
    works:'Checks your input live against a randomly selected subset of real password-strength rules from an expanded rule pool, updating pass/fail status on every keystroke.'},
  escape_room:{steps:['5 puzzles are randomly selected from a larger pool','Read each puzzle and use the hint if stuck','Type your answer — spacing/punctuation don\'t need to be exact','You get 4 attempts per puzzle'],
    demoIn:'Puzzle: "KHOOR ZRUOG", shift = 3',demoOut:'Answer: hello world',
    works:'Each puzzle tests a distinct cybersecurity skill; answers are normalized (punctuation/whitespace stripped) before comparison so near-correct typing isn\'t penalized.'},
  threat_triage:{steps:['Read the short scenario shown','Tap the category you think it belongs to','Read the explanation','Continue through 10 rounds'],
    demoIn:'"Hi, this is Microsoft Support calling about a virus..."',demoOut:'Correct: Social Engineering',
    works:'Draws from a bank of real-style scenarios spanning phishing, malware, social engineering, and legitimate messages, testing cross-category recognition rather than one narrow skill.'},
  redflag_hunter:{steps:['A mockup email or login page is shown','Click every element you think is a red flag','See which clicks were correct and what you missed','Continue through several scenarios'],
    demoIn:'[mockup PayPal email]',demoOut:'Correct: sender address, urgent subject line',
    works:'Each mockup has tagged clickable zones marked as genuine red flags or safe elements; correct clicks score points and incorrect clicks cost points, then every flag is revealed.'},
  scamcall_sim:{steps:['Read the call transcript as it unfolds','Choose your response at each decision point','See how your choice affects the call','Reach a safe resolution or see how the scam would have escalated'],
    demoIn:'"This is your bank, we need to verify your OTP..."',demoOut:'Correct: Hang up and call the bank\'s official number',
    works:'Branches a scripted call scenario based on your choices, showing the real consequence of each response — including what happens if you comply with a scammer\'s request.'},
};

const QUIZ_QUESTIONS = {
  password_quiz:[
    {q:'What is the minimum recommended length for a strong password?',opts:['6 characters','8 characters','12 characters','16 characters'],a:2,ex:'Security experts recommend at least 12 characters. Length is the single most important factor in password strength.'},
    {q:'Which of these passwords is the strongest?',opts:['P@ssword1!','correct-horse-battery-staple','X9#mK2','Admin2024'],a:1,ex:'A long passphrase of random words is stronger than a short complex password. Length beats complexity every time.'},
    {q:'What is password entropy?',opts:['How easy it is to remember','A measure of unpredictability','How many special characters it has','How long the password is'],a:1,ex:'Entropy measures randomness. Higher entropy means more possible combinations and a harder password to crack.'},
    {q:'Which practice is MOST dangerous?',opts:['Using a password manager','Reusing the same password across sites','Using long passwords','Enabling 2FA'],a:1,ex:'Password reuse means one breach exposes ALL your accounts.'},
    {q:'Which is the safest way to store passwords?',opts:['Write them in a notebook','Save them in a browser','Use a dedicated password manager','Remember them all'],a:2,ex:'A dedicated password manager encrypts your passwords with a master key only you know.'},
    {q:'What does 2FA protect against even if your password is stolen?',opts:['Nothing','Unauthorized login without the second factor','Password reuse only','Malware'],a:1,ex:'Even with your password, an attacker cannot log in without your phone or authenticator app.'},
    {q:'Which of these is a passphrase-style password?',opts:['Tr0ub4dor&3','purple-tiger-cloud-42','Pa$$w0rd','Qwerty123'],a:1,ex:'Passphrases combining random unrelated words are both long and memorable — a strong combination.'},
    {q:'Why are password strength meters on websites sometimes misleading?',opts:['They are always accurate','They may rate common patterns as strong just for having symbols and numbers','They test against real breach databases','They measure typing speed'],a:1,ex:'Basic meters check character variety, not real crackability. "P@ssword1!" often scores "strong" despite being on every cracking wordlist.'},
    {q:'What is credential stuffing?',opts:['Guessing passwords one by one','Automatically trying breached username/password pairs on many sites','Typing your password wrong repeatedly','A type of firewall'],a:1,ex:'Because people reuse passwords, attackers take one breached list and try it against many other services automatically.'},
    {q:'How often should you change a password that has NOT been involved in a breach?',opts:['Every single day','Only when there is reason to believe it was compromised','Every hour','Never, under any circumstance'],a:1,ex:'Forced frequent password changes often lead to weaker, predictable passwords. Change on suspicion of compromise, not on an arbitrary schedule.'},
  ],
  cyber_iq:[
    {q:'What does malware stand for?',opts:['Male software','Malicious software','Managed software','Manual software'],a:1,ex:'Malware is any software designed to harm, disrupt, or gain unauthorized access to a system.'},
    {q:'What is a zero-day vulnerability?',opts:['A flaw fixed in zero days','A flaw unknown to the vendor with no patch','One that lasts a day','A beginner issue'],a:1,ex:'Zero-day means the vendor has had zero days to fix it — the most dangerous kind of vulnerability.'},
    {q:'What does a VPN primarily do?',opts:['Encrypts your internet traffic','Speeds up browsing','Blocks ads','Compresses data'],a:0,ex:'A VPN creates an encrypted tunnel for your traffic, hiding activity from ISPs and hackers on public Wi-Fi.'},
    {q:'What is ransomware?',opts:['Software that slows your PC','Malware that encrypts your files and demands payment','A type of antivirus','Software that steals passwords'],a:1,ex:'Ransomware encrypts your files and demands a ransom for the decryption key.'},
    {q:'What is multi-factor authentication?',opts:['Using multiple passwords','Verifying identity with 2+ different factors','Having multiple accounts','Using a long password'],a:1,ex:'MFA combines something you know, have, and are — dramatically increasing security.'},
    {q:'What is a firewall?',opts:['A physical wall','Software/hardware that filters network traffic','An antivirus program','A type of encryption'],a:1,ex:'A firewall acts as a gatekeeper, allowing legitimate traffic and blocking suspicious connections.'},
    {q:'What is a DDoS attack?',opts:['Stealing data directly','Flooding a service with traffic to knock it offline','A type of virus','Encrypting files for ransom'],a:1,ex:'A Distributed Denial of Service attack overwhelms a target with traffic from many sources, making it unavailable to real users.'},
    {q:'What does "patching" a system mean?',opts:['Physically repairing hardware','Applying software updates that fix known vulnerabilities','Installing a new antivirus','Changing your password'],a:1,ex:'Patches close known security holes. Unpatched software is one of the most common ways attackers gain access.'},
    {q:'What is social engineering, broadly?',opts:['Writing secure code','Manipulating people rather than systems to gain access or information','Building social media apps','A type of encryption algorithm'],a:1,ex:'Social engineering exploits human trust and psychology instead of technical vulnerabilities.'},
    {q:'What does "encryption at rest" mean?',opts:['Encrypting data while it travels over the network','Encrypting data while it is stored on a disk','Encrypting only backups','A type of antivirus scan'],a:1,ex:'Encryption at rest protects stored data — so even if a drive is stolen, the data on it is unreadable without the key.'},
  ],
  social_eng:[
    {q:'A caller claiming to be from IT asks for your password to "fix an issue." This is:',opts:['Normal IT procedure','Pretexting — a fabricated scenario to gain trust','A firewall test','Two-factor authentication'],a:1,ex:'Real IT never needs your actual password. This is pretexting — inventing a believable scenario to manipulate you into compliance.'},
    {q:'You find a USB drive in a parking lot. What should you do?',opts:['Plug it in to see who it belongs to','Hand it to IT/security without plugging it in','Take it home','Format it first, then use it'],a:1,ex:'Dropped USB drives are a classic attack — plugging one in can silently install malware. Never plug in an unknown device.'},
    {q:'An email says "Your account will be deleted in 24 hours!" This tactic relies on:',opts:['Genuine urgency','Urgency and fear to bypass careful thinking','Standard company policy','Two-factor authentication'],a:1,ex:'Creating panic pressures people to act fast without verifying — a hallmark social engineering tactic.'},
    {q:'What is "tailgating" in a security context?',opts:['Following someone too closely while driving','Physically following an authorized person into a restricted area without their own access','A type of phishing email','A firewall rule'],a:1,ex:'Tailgating exploits politeness — people hold doors open, unknowingly giving unauthorized access to a secured area.'},
    {q:'Your "CEO" emails urgently requesting a wire transfer. Best first step?',opts:['Send it immediately, it\'s the CEO','Verify by calling the CEO directly on a known number','Reply asking for more details','Forward it to a coworker'],a:1,ex:'CEO fraud impersonates leadership. Always verify unusual money requests through a separate, trusted communication channel.'},
    {q:'What is "quid pro quo" in social engineering?',opts:['A legal contract','Offering something (like tech help) in exchange for information or access','A type of malware','A password policy'],a:1,ex:'Attackers offer a small favor to create a sense of obligation, making the target more likely to comply with a follow-up request.'},
    {q:'A "dream job" recruiter on LinkedIn asks for your bank details before an interview. This is:',opts:['Normal hiring practice','A recruitment scam exploiting excitement and urgency','Required for background checks','A sign of a serious employer'],a:1,ex:'Legitimate employers never need banking details before you\'re hired. This exploits eagerness and unfamiliarity with normal hiring steps.'},
    {q:'What makes spear phishing more dangerous than regular phishing?',opts:['It uses more technical hacking','It\'s personalized using real details about the specific target','It only targets companies','It doesn\'t use email'],a:1,ex:'Spear phishing uses real names, roles, and relationships to seem legitimate — making it far harder to spot than generic mass phishing.'},
    {q:'A caller already knows your name and the last 4 digits of your card. Should you trust them?',opts:['Yes, they clearly have your info already','No — hang up and call your bank\'s official number yourself','Only if they sound professional','Yes, but only share half your info'],a:1,ex:'Attackers often have partial data from breaches to sound credible. Real institutions won\'t mind you calling back on a verified number.'},
    {q:'Pretexting fundamentally relies on:',opts:['Advanced hacking tools','A fabricated, believable scenario that earns your trust','Breaking encryption','Physical theft'],a:1,ex:'Pretexting is entirely about the story — a convincing fake context that makes a request seem legitimate and routine.'},
  ],
  darkweb:[
    {q:'The dark web requires which browser to access?',opts:['Chrome','Firefox','Tor Browser','Safari'],a:2,ex:'Tor routes traffic through encrypted relays, allowing access to .onion sites on the dark web.'},
    {q:'Is everything on the dark web illegal?',opts:['Yes, entirely','No — it also includes legitimate privacy tools, forums, and journalism','Only in some countries','It doesn\'t exist'],a:1,ex:'The dark web is also used by journalists, activists, and privacy-conscious users in restrictive regimes — the technology itself is neutral.'},
    {q:'How do stolen passwords typically end up on the dark web?',opts:['Through data breaches of websites','They are typed there directly','Through your antivirus','They don\'t end up there'],a:0,ex:'When a website is breached, attackers often package and sell the stolen credentials on dark web marketplaces.'},
    {q:'Your email shows up in a breach alert. What\'s the right first step?',opts:['Ignore it, breaches are common','Change that password immediately and enable 2FA','Delete your email account','Wait to see if anything happens'],a:1,ex:'Immediate action limits damage — especially if that password was reused anywhere else.'},
    {q:'Why do dark web marketplaces often use cryptocurrency?',opts:['It\'s required by law','It offers pseudonymity, making transactions harder to trace','It\'s faster than credit cards','Cryptocurrency is illegal elsewhere'],a:1,ex:'Cryptocurrency transactions are harder (though not impossible) to trace back to a real identity compared to traditional payment methods.'},
    {q:'What is credential stuffing, as it relates to breach data?',opts:['Creating new passwords','Automatically trying breached username/password pairs across many other sites','Encrypting stolen data','A type of firewall'],a:1,ex:'Because of password reuse, one breached list can be "stuffed" into login forms across many unrelated services.'},
    {q:'What is a "dump" in dark web terminology?',opts:['A single stolen password','A large batch of stolen data sold together, often thousands of records','A type of malware','A backup file'],a:1,ex:'Dumps package large volumes of stolen credentials or card data for bulk sale.'},
    {q:'What\'s the real difference between "deep web" and "dark web"?',opts:['They are the same thing','Deep web is any unindexed content (like your inbox); dark web is a small, deliberately hidden portion of it','Deep web is illegal, dark web is legal','There is no difference in size'],a:1,ex:'The deep web is huge and mostly mundane (private databases, emails). The dark web is a much smaller, intentionally hidden slice requiring special access.'},
    {q:'You get a "your data was found on the dark web" popup. Best move?',opts:['Click it immediately to see details','Verify through a trusted, independent breach-checking site instead','Enter your password to confirm','Ignore all future security alerts'],a:1,ex:'Such alerts can themselves be phishing. Go directly to a trusted, known site rather than clicking an unsolicited link.'},
    {q:'Why do security researchers monitor dark web markets?',opts:['For entertainment','To track leaked data and warn affected organizations/users early','It\'s required by law everywhere','To buy stolen data for profit'],a:1,ex:'Monitoring dark web activity lets researchers spot breaches early and alert affected companies before wider damage occurs.'},
  ],
  incident:[
    {q:'Ransomware just encrypted your files. What\'s the correct FIRST action?',opts:['Pay the ransom immediately','Disconnect the device from the network immediately','Restart the computer','Post about it on social media'],a:1,ex:'Disconnecting stops the ransomware from spreading to other devices on your network before you do anything else.'},
    {q:'You entered your banking password on a phishing site. First step?',opts:['Do nothing, it\'s probably fine','Change that password immediately from a different, trusted device','Only worry if money goes missing','Delete your browser history'],a:1,ex:'Immediate password change limits the window an attacker has to use the stolen credential.'},
    {q:'Your email account was hacked and is sending spam. First step?',opts:['Ignore it, it will stop eventually','Recover account access and change the password immediately','Delete the account entirely','Wait for your contacts to complain'],a:1,ex:'Regaining control and changing the password stops the attacker from continuing to use the account.'},
    {q:'In incident response, what does the "Containment" phase mean?',opts:['Reporting the incident to police','Stopping the attack from spreading further','Restoring from backup','Writing a report afterward'],a:1,ex:'Containment isolates the threat so it can\'t cause more damage while you work on removing it.'},
    {q:'What is the correct order of the incident response framework?',opts:['Recover → Detect → Contain → Review → Eradicate','Detect → Contain → Eradicate → Recover → Review','Eradicate → Detect → Recover → Contain → Review','Review → Recover → Detect → Contain → Eradicate'],a:1,ex:'This is the standard framework: find the problem, stop it spreading, remove it, restore normal operation, then learn from it.'},
    {q:'Your phone was just stolen. First move?',opts:['Wait and hope it\'s returned','Remotely wipe the device and change your important passwords','Report it on social media first','Buy a new phone immediately'],a:1,ex:'Remote wipe protects your data before the thief can access anything, and password changes limit further damage.'},
    {q:'What does the "Eradication" phase specifically involve?',opts:['Disconnecting from Wi-Fi only','Removing the root cause of the incident from all affected systems','Filing an insurance claim','Buying new hardware'],a:1,ex:'Eradication means fully removing malware or the vulnerability everywhere it exists — not just addressing the visible symptom.'},
    {q:'Why does the "Review" phase matter after an incident is resolved?',opts:['It doesn\'t, once it\'s fixed you\'re done','It identifies how the breach happened so it doesn\'t repeat','It\'s only for insurance purposes','It\'s optional busywork'],a:1,ex:'Reviewing root cause and response effectiveness is how organizations (and individuals) actually get more secure over time.'},
    {q:'A coworker\'s account sends you a weird file unexpectedly. Best response?',opts:['Open it immediately, they\'re a coworker','Verify with them through a different channel (call, in person) before opening anything','Forward it to everyone as a warning','Reply asking what it is'],a:1,ex:'Compromised accounts often send malware to contacts. Verifying through a separate channel confirms whether they really sent it.'},
    {q:'Why are offline backups specifically valuable during a ransomware incident?',opts:['They are faster to access','Ransomware connected to your network can\'t reach or encrypt backups that are offline','They are cheaper than cloud backups','They don\'t need to be tested'],a:1,ex:'Ransomware spreads through connected systems. A backup that\'s physically or logically disconnected is the one thing it genuinely can\'t touch.'},
  ],
  hygiene:[
    {q:'Why do software updates matter for security specifically?',opts:['They add new features only','They patch known vulnerabilities attackers actively exploit','They make your device faster','They are optional and rarely important'],a:1,ex:'Unpatched software is one of the most common ways attackers gain access — updates close known, publicly documented holes.'},
    {q:'What does 2FA actually protect against?',opts:['Nothing extra beyond a password','Someone logging in even if they already have your password','Only phishing emails','Malware infections'],a:1,ex:'2FA requires a second factor (like your phone) that an attacker won\'t have even if your password leaks.'},
    {q:'Why is checking app permissions important?',opts:['It isn\'t, apps only ask for what they need','Apps often request access (mic, contacts, location) far beyond what they actually need','It slows down your phone','Permissions can\'t be changed anyway'],a:1,ex:'Many apps over-request access. Reviewing permissions limits what a compromised or shady app could actually do.'},
    {q:'What\'s the risk of installing random browser extensions?',opts:['They use extra battery only','They can read and modify everything you see and type on every website','They are always reviewed by the browser store first','There is no real risk'],a:1,ex:'Browser extensions often run with broad page access — a malicious one can capture passwords and payment details in real time.'},
    {q:'Why should you log out of accounts on shared or public devices?',opts:['It\'s not necessary if you close the tab','Active sessions can remain accessible to the next person who uses the device','Logging out slows down the device','Shared devices are always safe'],a:1,ex:'Closing a tab doesn\'t always end a session — the next user could still access your account without logging in.'},
    {q:'What is the point of the "3-2-1" backup strategy?',opts:['3 different passwords for backups','3 copies of data, on 2 different media types, with 1 stored offsite/offline','3 backups per day','2 copies and 1 password manager'],a:1,ex:'This spread protects against device failure, local disasters, and ransomware all at once — no single point of failure.'},
    {q:'Why is repeatedly clicking "Remind me later" on updates risky?',opts:['It isn\'t risky at all','It leaves known, already-public vulnerabilities unpatched and exploitable','It only affects app looks','Updates always break things'],a:1,ex:'Once a vulnerability is publicly known and patched, delaying the update just gives attackers a longer window to exploit it on your device.'},
    {q:'What should you do before discarding an old phone or laptop?',opts:['Just delete a few files','Fully wipe it with a factory reset, not just delete individual files','Nothing, old devices are safe','Remove the battery only'],a:1,ex:'Deleted files can often be recovered. A proper factory reset/wipe is needed to actually clear sensitive data.'},
    {q:'Why is saved auto-fill password data risky on a shared computer?',opts:['It isn\'t risky','The next user can access your saved logins without ever knowing your password','Auto-fill doesn\'t work on shared computers','It only affects browsing speed'],a:1,ex:'Auto-fill bypasses the password prompt entirely for anyone using that browser profile next.'},
    {q:'What\'s the safest habit around unusual links, even from known contacts?',opts:['Always trust links from people you know','Verify separately if the message feels unusual, since accounts get compromised','Click immediately, contacts are always safe','Only worry about links from strangers'],a:1,ex:'Compromised accounts frequently send malicious links to the real owner\'s contacts — familiarity alone isn\'t proof of safety.'},
  ],
  privacy:[
    {q:'What is a "data broker"?',opts:['A stockbroker for tech companies','A company that collects and sells personal data gathered from many sources','A type of antivirus','A government privacy regulator'],a:1,ex:'Data brokers compile profiles from public records, app data, and purchases, then sell that information to advertisers and others.'},
    {q:'What does metadata reveal about a photo, even without seeing its content?',opts:['Nothing at all','Location, device model, and the exact timestamp it was taken','Only the file size','The photographer\'s name only'],a:1,ex:'EXIF metadata embedded in photos can reveal exactly where and when a picture was taken, even if the image itself shows nothing sensitive.'},
    {q:'What do third-party tracking cookies actually do?',opts:['Store your password securely','Follow your browsing activity across multiple unrelated websites','Speed up page loading only','Nothing without your explicit consent'],a:1,ex:'Third-party cookies let advertisers build a profile of your behavior by tracking you as you move between different sites.'},
    {q:'What does "anonymized data" really guarantee?',opts:['Complete, permanent anonymity','Very little — it can often be re-identified by combining it with other datasets','Legal immunity for the company','Nothing is collected at all'],a:1,ex:'Studies repeatedly show "anonymized" datasets can often be re-identified when cross-referenced with other available data.'},
    {q:'Why does a weather app\'s location permission matter even for something simple?',opts:['It doesn\'t matter at all','Continuous background access can build a detailed movement profile over time','Weather apps never request location','It only affects battery life'],a:1,ex:'Ongoing location access — even for something as innocent as weather — can quietly build a precise history of everywhere you go.'},
    {q:'What\'s the privacy risk of public Wi-Fi login pages asking for your email?',opts:['There is no risk','That email often gets added to marketing/data-broker lists you never explicitly agreed to','It improves your connection speed','It\'s required by law everywhere'],a:1,ex:'Free Wi-Fi "sign in with email" pages are frequently a data-collection tactic disguised as a login requirement.'},
    {q:'Why should social media privacy settings be reviewed periodically?',opts:['They never change once set','Platforms frequently change defaults, sometimes reopening what you\'d locked down','It\'s a one-time setup only','Privacy settings don\'t affect anything important'],a:1,ex:'Platform updates can quietly reset or add new sharing defaults — a setting that was private last year may not be anymore.'},
    {q:'What\'s a realistic risk of publicly sharing your birthday, pet\'s name, and hometown?',opts:['No real risk, it\'s just fun trivia','These are common security-question answers attackers use to reset your accounts','It only affects birthday reminders','Only celebrities need to worry about this'],a:1,ex:'These exact details are the standard answers to account-recovery security questions — publicly posting them hands attackers a shortcut.'},
    {q:'What does a GDPR-style "right to be forgotten" allow?',opts:['The right to forget your own password','Requesting that a company delete the personal data they\'ve collected about you','Free antivirus software','The right to anonymous browsing by default'],a:1,ex:'This right lets individuals formally request deletion of their personal data from a company\'s records.'},
    {q:'Why is reading an app\'s data-sharing practices important, not just its permissions?',opts:['They are the same thing','Permissions show what it can access; data-sharing shows who else receives that data','Data-sharing policies don\'t really exist','Only enterprise apps share data'],a:1,ex:'An app might only request minimal permissions but still sell or share whatever data it does collect with third parties.'},
  ],
  device_quiz:[
    {q:'What does "encryption at rest" protect against on a stolen phone?',opts:['Nothing if the phone is locked','Someone extracting the storage and reading your files without the passcode','Battery drain','Screen cracking'],a:1,ex:'Even if someone physically removes the storage chip, encryption at rest makes the data unreadable without the correct passcode/key.'},
    {q:'Why is a 6-digit PIN generally safer than a 4-digit one?',opts:['It isn\'t, they\'re equally safe','It has far more possible combinations, making brute-force guessing much harder','6 digits are easier to remember','It only matters for old phones'],a:1,ex:'A 6-digit PIN has 1 million possible combinations versus just 10,000 for a 4-digit one — a huge jump in brute-force difficulty.'},
    {q:'What\'s the risk of leaving Bluetooth discoverable at all times?',opts:['No risk, Bluetooth is always safe','It increases exposure to nearby attacks like unauthorized pairing attempts','It only drains battery','It improves signal strength'],a:1,ex:'A constantly-discoverable device is more visible to nearby attackers probing for vulnerable Bluetooth connections.'},
    {q:'Why is AirDrop/Nearby Share set to "Everyone" risky in public?',opts:['It isn\'t risky at all','Strangers nearby can send unsolicited files or links directly to your device','It only works with contacts anyway','It disables your phone\'s security'],a:1,ex:'"Everyone" visibility lets any nearby stranger attempt to send you files directly — including malicious ones.'},
    {q:'What does biometric lock (fingerprint/face) NOT protect against?',opts:['Random guessing attempts','Someone holding you or your unlocked device physically to force authentication','Basic screen theft','Casual snooping'],a:1,ex:'Biometrics stop guessing attacks well, but can\'t stop someone physically forcing your finger or face onto the sensor — unlike a PIN only you know.'},
    {q:'Why should app permissions be reviewed regularly, not just at install?',opts:['They never change after install','Apps can request new permissions in updates that weren\'t there originally','Reviewing them once is always enough','Permissions are irrelevant after installation'],a:1,ex:'App updates can quietly add new permission requests — a periodic review catches scope creep you didn\'t explicitly approve.'},
    {q:'What\'s the real risk of charging your phone at a random public USB port?',opts:['No risk, USB only carries power','"Juice jacking" — a compromised port can transfer data or malware, not just power','It charges your phone slower','It only affects older phones'],a:1,ex:'USB connections carry both power and data — a tampered public port can potentially access or infect your device while it charges.'},
    {q:'Why is enabling "Find My Device" important before a device is ever lost?',opts:['It doesn\'t need to be set up in advance','It cannot be activated remotely after the fact — it must already be on to help','It only works if the phone is still charged','It\'s only useful for finding lost keys'],a:1,ex:'Find My Device relies on settings enabled beforehand — you cannot turn it on retroactively after a device is already lost or stolen.'},
    {q:'What does a screen lock protect beyond "someone picking up your phone"?',opts:['Nothing else really','Unauthorized access to saved passwords, banking apps, and 2FA codes if lost or stolen','Only your photos','It only matters for work phones'],a:1,ex:'A phone often holds saved logins, banking apps, and even 2FA codes — a screen lock is often the only thing standing between a thief and all of it.'},
    {q:'Why should old, unused apps be deleted rather than left installed?',opts:['They take up storage space only','Unmaintained apps stop receiving security updates and become a growing entry point over time','Old apps are always safe once installed','It doesn\'t matter if you never open them'],a:1,ex:'Abandoned apps stop getting security patches, so any vulnerability discovered in them later stays open indefinitely on your device.'},
  ],
  wifi_quiz:[
    {q:'Why is WPA3 better than WEP?',opts:['WPA3 has a nicer name','WEP can be cracked in minutes; WPA3 uses much stronger, modern encryption','They are the same technology','WEP is actually newer'],a:1,ex:'WEP is critically outdated and crackable in minutes with free tools. WPA3 uses modern encryption that\'s vastly harder to break.'},
    {q:'What is a common router vulnerability if the admin login is never changed?',opts:['Nothing, admin logins are always unique','Default admin passwords are publicly listed online by brand and model','Routers don\'t have admin logins','It only affects business routers'],a:1,ex:'Default credentials for nearly every router model are searchable online — leaving them unchanged is an open door.'},
    {q:'What does WPS (Wi-Fi Protected Setup) risk?',opts:['It has no real risk','Its PIN can be brute-forced, bypassing even a strong Wi-Fi password entirely','It only works with Apple devices','It automatically encrypts all traffic'],a:1,ex:'WPS PINs have a known design flaw allowing brute-force attacks that bypass your actual (possibly very strong) Wi-Fi password.'},
    {q:'What is a "rogue access point"?',opts:['A router that\'s out of range','A fake Wi-Fi network set up to look legitimate and intercept traffic','A router with strong encryption','A backup Wi-Fi network'],a:1,ex:'Rogue access points impersonate real networks to trick devices into connecting, letting an attacker intercept everything sent.'},
    {q:'On public Wi-Fi, what\'s the safest practice?',opts:['Do online banking freely, it\'s fine','Use a VPN to encrypt your traffic, since the network itself may be monitored','Turn off your phone\'s antivirus','Connect to any open network without a password'],a:1,ex:'Public networks are often unencrypted or monitored — a VPN protects your traffic even if the network itself isn\'t trustworthy.'},
    {q:'Why should smart plugs and cameras go on a separate guest network?',opts:['It isn\'t necessary','If compromised, it isolates them from your main devices, files, and passwords','IoT devices don\'t connect to Wi-Fi','It makes them work faster'],a:1,ex:'IoT devices are frequently poorly secured — network segmentation limits the damage if one gets compromised.'},
    {q:'What is an "evil twin" attack?',opts:['A virus that copies itself','A fake hotspot broadcasting the same name as a real, trusted one','A type of ransomware','A firewall misconfiguration'],a:1,ex:'Evil twins trick devices into auto-connecting to a malicious network because the name matches one you already trust.'},
    {q:'Why does UPnP (Universal Plug and Play) pose a security risk?',opts:['It doesn\'t pose any risk','It can let malware silently open ports on your router without your knowledge','It only affects gaming consoles','It\'s required for internet access'],a:1,ex:'UPnP lets devices (and potentially malware) open ports automatically — a convenience feature that can be silently abused.'},
    {q:'What does "network segmentation" mean in a home Wi-Fi context?',opts:['Having multiple routers for speed','Splitting devices across separate networks so a breach on one doesn\'t expose all of them','Turning off Wi-Fi at night','Using a longer Wi-Fi password'],a:1,ex:'Segmentation (e.g. guest network for IoT, main network for personal devices) limits how far a single compromised device can reach.'},
    {q:'You see an unfamiliar device connected to your router. First move?',opts:['Ignore it, it\'s probably fine','Check the device list, then change your Wi-Fi password and remove it','Unplug the router permanently','Call the police immediately'],a:1,ex:'An unrecognized connected device could mean unauthorized access — changing the password immediately cuts off that access.'},
  ],
  digital_footprint:[
    {q:'What is a "digital footprint"?',opts:['Only the photos you post','The entire trail of data you leave online — posts, comments, metadata, accounts, search history','Your IP address only','A type of malware'],a:1,ex:'Your footprint is everything traceable back to you — not just what you actively post, but metadata, old accounts, and data others post about you.'},
    {q:'You deleted a photo from Instagram 2 years ago. Is it really gone?',opts:['Yes, deleted means gone forever','Not necessarily — it may exist in caches, screenshots, archives, or backups elsewhere','Only Instagram employees can see it now','It becomes public domain'],a:1,ex:'Once something is online, it can be cached, screenshotted, archived (e.g. Wayback Machine), or re-shared before you delete it — deletion isn\'t always total.'},
    {q:'What is EXIF data hidden inside a photo?',opts:['The photo\'s filter settings','Metadata like GPS location, device model, and timestamp embedded in the file','A watermark','The photo\'s file size only'],a:1,ex:'Photos taken on phones often embed GPS coordinates and device info invisibly — sharing the original file can reveal exactly where you were.'},
    {q:'Why is using the same username everywhere a footprint risk?',opts:['It is not a risk at all','It lets anyone link all your accounts together into one profile','Usernames cannot be searched','Only passwords matter, not usernames'],a:1,ex:'A consistent username across platforms makes it trivial to connect your gaming, dating, and professional accounts into a single identity profile.'},
    {q:'What can someone learn from your public LinkedIn profile alone?',opts:['Nothing sensitive','Your workplace, job title, colleagues, and career timeline — useful for building a targeted scam','Your home address always','Your bank details'],a:1,ex:'LinkedIn is a goldmine for social engineers — it gives real names, roles, and relationships they can impersonate or exploit convincingly.'},
    {q:'What is "doxxing"?',opts:['A type of firewall','Publicly revealing someone\'s private information (address, phone, workplace) without consent, usually to harass them','A password manager','A legal term for hacking'],a:1,ex:'Doxxing compiles someone\'s scattered public footprint into one place specifically to enable harassment or intimidation.'},
    {q:'You use a work email to sign up for a personal shopping site that later gets breached. What is the risk?',opts:['None, it is just a shopping site','Your work email + password pattern is now exposed, which can be used to target your employer too','Only the shopping site is affected','Breaches never involve email addresses'],a:1,ex:'Mixing personal signups with a work email links your professional identity to breaches that have nothing to do with your employer\'s security — and password reuse makes it worse.'},
    {q:'What is the safest approach to old, unused online accounts?',opts:['Leave them — they are harmless if forgotten','Delete or deactivate them, since forgotten accounts with old passwords are an easy target','Change the username only','Nothing can be done about old accounts'],a:1,ex:'Old accounts often use outdated, weak, or reused passwords and rarely get security updates — they are a quiet way into your identity long after you forgot they existed.'},
    {q:'A stranger could learn your daily routine mainly from:',opts:['Nothing, routines are private by default','Recurring public posts — gym check-ins, commute photos, "back to school/work" posts — patterned over time','Only from stalking in person','Government records'],a:1,ex:'Individually, posts feel harmless. Patterned over weeks, they can reveal exactly where you are and when — which is why routine-based oversharing is a real risk.'},
    {q:'What is the single most effective way to reduce your digital footprint going forward?',opts:['Never using the internet again','Regularly auditing what\'s public, deleting what\'s unnecessary, and thinking before each post — not just reacting after a problem','Using a different name on every site','Turning off your phone once a week'],a:1,ex:'A footprint builds up slowly through years of small choices — the fix is the same: pause before posting, and periodically clean up what\'s already out there.'},
  ],
};

const EDU_CARDS = [
  {tag:'Tip of the Day', title:'Enable 2FA on every account — a stolen password alone won\'t be enough.'},
  {tag:'Did You Know?', title:'A hacker attacks a computer every 39 seconds on average, somewhere in the world.'},
  {tag:'Threat of the Week', title:'QR code phishing ("quishing") is rising sharply — always verify before scanning unknown codes.'},
];

const STATS_DEFAULT = {
  urls:1284, passwords:742, emails:963, files:318, qr:201, headers:410,
  threats:2891, phishing:1456, weakpw:892, suspicious:634, malwarefound:178,
  quizzes:847, games:1205, totalweek:3847, protected:5621, prevented:756, awareness:78
};

const END_SCREENS = {
  cipher:{title:'Cipher Master!',msg:'You cracked shifted messages — you\'ve got a real feel for how Caesar ciphers work now.',tip:'Modern encryption builds on these same substitution principles, just exponentially more complex.',
    learned:['How a Caesar shift transforms letters — and how to reverse it by shifting backward','That the same logic scales to any shift amount, not just one you\'ve memorized','Why this simple cipher is trivial to break today with basic pattern analysis'],
    levelUp:['Try Crack the Code next — same cipher, but now you have to find the shift yourself','Modern encryption (AES-256) uses these same substitution ideas, just far more complex — worth reading about','Challenge a friend to beat your score']},
  cipher_practice:{title:'Keep Practicing!',icon:'💪',msg:'Caesar ciphers take a bit of reps to click — you\'re closer than you think.',tip:'Try working backward from the last letter of the alphabet if the shift feels large — it\'s often easier than counting forward.',
    learned:['The core mechanic: every letter shifts by the same fixed amount','How to use the Hint button to work out one letter, then apply that shift to the rest'],
    levelUp:['Play again — the practice round\'s worked example is always there to revisit','Try a smaller shift value mentally first before attempting the full word']},
  crack_code:{title:'Code Breaker!',msg:'You cracked the cipher like a pro cryptanalyst. You now understand frequency analysis.',tip:'Modern AES-256 encryption would take longer than the age of the universe to crack by brute force.'},
  phishing_detect:{title:'Phishing Proof!',msg:'You spotted every trap the hackers laid. Cybercriminals won\'t fool you again.',tip:'Always hover over links before clicking to verify the real destination domain.'},
  password_quiz:{title:'Password Expert!',msg:'Your knowledge of password security is stronger than ever. Every account is safer now.',tip:'Enable 2FA on every account — a stolen password alone won\'t be enough.',
    learned:['Length beats complexity — a long passphrase resists cracking better than a short, symbol-heavy password','Password strength meters can be misleading and rate common patterns as "strong"','Credential stuffing means one breach can compromise every account using that same password','2FA stops most account takeovers even if your password leaks'],
    levelUp:['Install a password manager (Bitwarden, 1Password) and let it generate every password from now on','Turn on 2FA using an authenticator app, not SMS, on your email and banking apps first','Run your email through haveibeenpwned.com to check for existing breaches','Try the Password Generator Game to practice building strong passwords in real time']},
  cyber_iq:{title:'Cyber IQ Certified!',msg:'Your awareness of cybersecurity threats and defenses is now measurably higher.',tip:'Stay updated — follow trusted cybersecurity news sources regularly.',
    learned:['The core vocabulary of cybersecurity — firewalls, DDoS, patching, encryption, social engineering','Most attacks target people, not just systems — awareness is a real defense layer','Unpatched software is one of the most common ways attackers gain access','Encryption at rest protects stored data even if a device is physically stolen'],
    levelUp:['Take the Social Engineering and Incident Response quizzes next to go deeper on the human side of security','Turn on automatic updates for your OS and every app you use regularly','Follow a reputable security news source (e.g. KrebsOnSecurity, The Hacker News) to stay current','Try the Escape Room game to apply this knowledge under pressure']},
  wifi_quiz:{title:'Network Secured!',msg:'You now understand what actually makes Wi-Fi secure, not just a list of settings to toggle.',tip:'Change your router\'s default admin password today if you haven\'t already.',
    learned:['Default router passwords and SSIDs are publicly known and should always be changed','WPA3/WPA2 encryption is essential — WEP and WPA are crackable in minutes','WPS and rogue/evil-twin access points are common real-world attack vectors','Network segmentation keeps a compromised IoT device from reaching your main devices'],
    levelUp:['Log into your router\'s admin panel today and check for a pending firmware update','Review the connected-devices list and remove anything you don\'t recognize','Set up a guest network if you haven\'t already, especially for smart-home devices','Use a VPN by default on public Wi-Fi networks']},
  social_eng:{title:'Human Firewall Activated!',msg:'You can now recognize psychological manipulation. You are the last line of defense.',tip:'Always verify sensitive requests through a separate communication channel.',
    learned:['The core tactics: pretexting, baiting, urgency, tailgating, CEO fraud, and quid pro quo','Attackers exploit trust and authority, not technical flaws — no firewall stops a convincing phone call','Legitimate organizations never pressure you to act instantly or bypass normal verification','Spear phishing uses real personal details to make a scam far more convincing'],
    levelUp:['Agree on a verification method with family/coworkers for any unusual money or password request — a codeword or callback number','Take the Incident Response Quiz next to learn what to do if a social engineering attempt succeeds','Practice spotting these patterns in the Threat Triage and Scam Call Simulator games','Share this quiz with someone less tech-savvy in your life — they\'re the most common target']},
  darkweb:{title:'Dark Web Demystified!',msg:'You now know fact from fiction about the dark web.',tip:'Check haveibeenpwned.com regularly to see if your email appears in data breaches.',
    learned:['The difference between the "deep web" (anything unindexed, like your inbox) and the much smaller "dark web"','How stolen data (credential dumps) gets bought, sold, and reused via credential stuffing','Fake "your data was found on the dark web" alerts are themselves a common scam tactic','Why security researchers monitor dark web markets to warn organizations early'],
    levelUp:['Check haveibeenpwned.com with your main email addresses right now','If any account shows up breached, change that password immediately — especially if reused elsewhere','Turn on breach alerts so you\'re notified automatically in the future','Take the Digital Footprint Awareness Quiz to see what else about you might already be exposed']},
  incident:{title:'Incident Ready!',msg:'You now know exactly what to do when a cyberattack hits.',tip:'Keep offline backups — ransomware cannot encrypt what it cannot reach.',
    learned:['The incident response framework: Detect → Contain → Eradicate → Recover → Review','Why disconnecting from the network is often the correct first move, not panicking or paying','Eradication means removing the root cause everywhere, not just disconnecting the symptom','Offline backups are the one thing ransomware genuinely cannot reach and encrypt'],
    levelUp:['Set up at least one backup that is NOT connected to your network or synced live to the cloud','Write down — on paper, not just mentally — the first 3 steps you\'d take if hacked today','Try the Cyber Escape Room game to rehearse incident-response thinking under pressure','Review your device\'s remote-wipe settings so you\'re ready if a device is ever stolen']},
  hygiene:{title:'Digitally Clean!',msg:'You now understand why these daily habits actually matter, not just that you should do them.',tip:'Do a monthly security audit of permissions, updates, and account logins.',
    learned:['Small daily habits — screen locks, updates, unique passwords — compound into real protection','Public Wi-Fi and unreviewed app permissions are common but overlooked risk points','The 3-2-1 backup rule: 3 copies of your data, 2 different media types, 1 stored offsite','Compromised accounts commonly send malicious links to their own real contacts'],
    levelUp:['Pick one habit from this quiz you\'re weakest on and fix just that one this week','Set a recurring monthly reminder to review app permissions and update everything','Move on to the Privacy & Data Protection Quiz to lock down what\'s visible to others','Try the Password Generator Game to build the muscle memory for strong passwords']},
  privacy:{title:'Privacy Locked!',msg:'You now understand how your data actually gets collected and exposed, not just that it can be.',tip:'Use a VPN on public Wi-Fi and consider a privacy-focused browser like Firefox.',
    learned:['Default privacy settings on most platforms are rarely the safest option, and they can quietly change','Third-party tracking cookies follow you across sites you never gave direct permission to','"Anonymized" data is not the same as truly anonymous — it can often be re-identified','2FA and up-to-date recovery info are what let you actually regain a compromised account'],
    levelUp:['Go to your Google/Facebook "connected apps" settings today and revoke anything you don\'t recognize','Turn off location sharing on your most-used social app if it\'s still on by default','Move to the Device & Mobile Security Quiz next to secure the hardware, not just the accounts','Revisit your privacy settings after any major app update — defaults change often']},
  device_quiz:{title:'Device Hardened!',msg:'You now understand why these device settings actually matter.',tip:'Enable full-disk encryption — if stolen, your data stays private.',
    learned:['A 6-digit PIN has 1 million combinations versus 10,000 for a 4-digit one — small change, big difference','Full-disk encryption makes stolen data unreadable without your password','Bluetooth and AirDrop left wide open expand your attack surface in public spaces','Public USB charging ports carry a real "juice jacking" data-theft risk'],
    levelUp:['Turn on full-disk encryption today if it isn\'t already active — it\'s usually one setting away','Set up Find My Device / Find My iPhone remote wipe if you haven\'t','Carry your own charger or a USB data-blocker for public charging ports','Try the Metadata Stripper tool to see what your own photos are quietly revealing']},
  digital_footprint:{title:'Footprint Aware!',msg:'You now understand how much of your identity is discoverable — and what to do about it.',tip:'Google your own name periodically to see what a stranger would find.',
    learned:['Deleted content isn\'t always gone — caches, archives, and screenshots can outlive the original post','Photos carry hidden EXIF metadata, including GPS location, unless it\'s stripped before sharing','Reusing the same username everywhere lets strangers link all your accounts into one profile','Patterned public posts (routines, check-ins) reveal more about your life than any single post alone'],
    levelUp:['Search your own name and usual usernames in a search engine and see what comes up','Check your phone\'s camera settings and turn off location tagging for photos you plan to share','Deactivate or delete accounts you no longer use instead of leaving them dormant','Try the Metadata Stripper tool to see exactly what your own photos are exposing']},
  morse:{title:'Morse Master!',msg:'You decoded Morse using the reference chart — one of the oldest digital languages, and you\'ve got it now.',tip:'Morse code is still actively used in aviation and amateur radio communications worldwide.',
    learned:['How dots and dashes map to letters, and how to read them back into words','Why short, distinct patterns (like S and O) became the basis of global distress signals'],
    levelUp:['Try Binary Blitz next to practice a different encoding, this time inferred from context','See how many letters you can recognize on the reference chart without looking twice']},
  morse_practice:{title:'Keep Practicing!',icon:'💪',msg:'Morse code just takes repetition — the patterns start sticking faster than you\'d expect.',tip:'Focus on a few letters at a time — E (.) and T (-) are the shortest and easiest to spot first.',
    learned:['The basic idea: every letter is a unique pattern of dots and dashes','How to use the reference chart and Hint button together to build outward from one letter'],
    levelUp:['Play again — the reference chart and practice round are always there','Try memorizing just S O S first, then expand from there']},
  binary:{title:'Binary Brain!',msg:'You decoded binary using riddle clues — the fundamental language of every computer, and you\'ve got it now.',tip:'All data — text, images, video, code — is ultimately stored as binary 0s and 1s.',
    learned:['How each letter maps to an 8-digit binary byte','How to combine context clues with a partial decode to confirm an answer quickly'],
    levelUp:['Try Morse Rush next to practice a different encoding, this time with a full reference chart','Look up the ASCII table to see the full mapping of characters to binary']},
  binary_practice:{title:'Keep Practicing!',icon:'💪',msg:'Binary decoding is a skill that clicks with repetition — you\'re building it right now.',tip:'Use the riddle first to guess the word, then use the binary just to confirm you\'re right.',
    learned:['The basic idea: every character is represented as an 8-digit binary byte','How riddles + a first-letter hint make the decode much more approachable'],
    levelUp:['Play again — the practice round\'s worked example is always there to revisit','Try solving just the riddle first before even looking at the binary code']},
  passgen:{title:'Password Master Unlocked!',msg:'You built a password that passed every rule with attempts to spare. Your passwords are now unbreakable.',tip:'Use a password manager to store unique strong passwords for every account.'},
  escape_room:{title:'ESCAPED!',msg:'You solved 5 cybersecurity puzzles and escaped the locked system.',tip:'Real incident responders follow: Identify, Protect, Detect, Respond, Recover.'},
  threat_triage:{title:'Triage Complete!',msg:'You correctly categorized real-world threats under pressure — pulling together everything NEXUS has taught you.',tip:'When in doubt in real life: verify independently before you trust, click, or comply.'},
  redflag_hunter:{title:'Flag Hunter!',msg:'You spotted the red flags hiding in plain sight — the visual instinct that catches real phishing attempts.',tip:'Always check the actual sender address and hover over links before trusting anything urgent.'},
  scamcall_sim:{title:'Call Survived!',msg:'You navigated a simulated scam call and came out the other side without falling for it.',tip:'Real banks and government agencies never ask you to read out an OTP over the phone.'},
};
